### ISSUE TITLE
Feature Request - Small-caps N/S/E/W on Street Shield 

### ISSUE THREAD

**Issue by theRadison** [TheCre8r/WME-Road-Shield-Helper#33] opened 2021-07-16 14:02 UTC
I have a small handful of non-standard named parkways/expressways that I've put shields on that regex won't and I don't expect it to catch.  I'm sure this would also be the case in NYS as well.  But no easy way to put the Small-Caps directions on them.  Can we incorporate just the N/S/E/W buttons on the road shield popup?

**Comment by TheCre8r** [comment] 2021-07-16 14:06
This is a duplicate of #29

**Closed** 2021-07-16 14:07 UTC
Labels: duplicate
